# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58d636bbb6458ed4d0b78d029f44994edd6b66b660d081d5539958cf34aade1068cd151021fe81d953b31bd3597cc7137fa8ca8d57e39df9b20aa89021521724

test:
  secret_key_base: 32f74b811ff3b5d68577ceb280253c912b40ad7eff45131e4a2ba477489ca6254a7a3196ec6108268179a84078fbda02668f4a10d6ae3d9475d5dabb6bd80b6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
